### ISSUE TITLE
Increasing wait time to 2 seconds makes the script work consistently for a particular website.

### ISSUE THREAD

**Issue by dfgshdsfh** [RichKMLS/Scrollbar-Fixer#1]
I really appreciate you putting together this script, so far it has worked better than other I've tried.

One page that seemed to get past the script was the following: https://www.hackster.io/news/arctos-robotics-aims-to-design-a-3d-printable-robot-arm-as-easy-as-building-lego-03559e924d70

The page has that typical stupid signup popup that also removes the scrollbars. So after using ublock origin's element blocker to kill it with:
```
! 2023-05-12 https://www.hackster.io
www.hackster.io##.styles__dialog__1KnWX
```
There's no longer element to trigger returning the scrollbars.

Using your script, the scrollbars would remain lost. However trying on various other pages pages would usually have the scrollbars hidden, but not always which tipped me off that this appears to be a timing issue.

Changing the script wait time from 1000ms to 2000ms on line: https://github.com/RichKMLS/Scrollbar-Fixer/blob/d77e102476176ed116dc629b6d5a6d56dad99c38/ScrollBarFixer.js#LL52C1-L52C42 seems to address this particular website perfectly.

**Comment by GithubUserAccountAmazing** [comment]
Thank you for your feedback.

I have addressed the issue you mentioned with commit 48839e77bf7558a307661cc6c47e8a09fcd04b7a. In this update, I added a retry feature to the fixScrollbars function. Now, if the scrollbars are not fixed after the first attempt, the function will wait for another second and try again. I also added a counter variable and an extratries variable so you can adjust the number of extra tries by changing the value of the extratries variable. This should help fix scrollbars on websites that need a longer timeout.

I hope this update solves the problem you were having. Please let me know if you have any other feedback or issues. I appreciate your help in improving the script.
